public class CountDNANucleotide {
	public String count(String s) {
		char[] arr = s.toCharArray();
		int a = 0;
		int c = 0;
		int g = 0;
		int t = 0;
		for(char z:arr) {
			if(z == 'A')
				a++;
			else if(z == 'C')
				c++;
			else if(z == 'G')
				g++;
			else
				t++;
		}
		return a + " " + c + " " + g + " " + t;
	}
	public static void main(String args[]) {
		CountDNANucleotide obj = new CountDNANucleotide();
		System.out.println(obj.count("ATGGAATGTTCTGGGTATCCTGGAACTGACGCACTAATTGTGAACCAATCGTTAGCTTCACGTTTCGTGGTGGGCTTCAATAATTCCGGTCGTCAATATTTAGCCCCGTAGGTTGGGGGCGGACGATTGATATCAGAACGTGGTTGTCATACCCTTCTATGATAATCGTGGTTCTGTTTAGACCTTCAGACGACTTGCAAACCGCTCGTTTGAATCCAGTCCGAGTTGCTAGCGGGCAGGCATTACAGGGGCTGATAGGCGTGCCCGGCGGCCCTGTGATCGAGGTAACGTCGTAACCAGTCTCAACTGATAGCCCGCAGTCGAATTTGAGGCTAAACGGACAGCGTATTCGAGATCTAACGCATTTACAATACAGCCTTGACCCGTTCTATCTTTCGTATCTTAATAATACTTTGGACATGTCCCTTTACGAACCCAACCAAGGGCGCAAACAAGGGCCGTTTATATTGTCACACGCCTGAGGCGAACTCTTCAACGGCTATTCCGTCGTAAACCTTGACGAAACGCATGTGTCTTTCGCACCGGACGCTCCACAGGATGGCTAATCCAGAAGGGACGCGACGTGAATGAGGTGCAGTGGGCATAGATTCGGAATCGGGCGCAGGATGTTCGCTTACAGACTCCTGAGAGTGAGTATATAGTAAGAATTAGCTGTTGAGATGATGAAGCCCAAATAGCTGTCTATCCGGCTTCGCCAGCCGTACACTACCGTGGTATTCACGAGCCCAGTCGTCCATACTGCCTCAACTACGTGGGATCAGAATCCTGAGGTCTCTCTCTTTAAGTCGGACGG"));
	}
}